import Head from "next/head";
import StoreFront from "~/components/StoreFront";
import "~/styles/globals.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Busy Boards</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <StoreFront />
      </main>
    </>
  );
}
